config/routes.rb
Rails.application.routes.draw do
  root "chatroom#index"
  get "login", to: "sessions#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
validates :username, presence: true, length: { minimum:3, maximum: 15 },
            uniqueness: { case_sensitive: false }
has_many :messages
has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController

    def index

    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new

    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/index.html.erb
<h4 class="ui center aligned large icon header">
  <i class="circular orange coffee icon"></i>
  Say something
</h4>
<div class="ui two column grid">
  <div class="twelve wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content">
        <div class="ui feed">
          <div class="event">
            <div class="content">
              <div class="summary">
                <a>Elliot Fu</a> added <a>Jenny Hess</a> as a friend
              </div>
            </div>
          </div>
          <div class="event">
            <div class="content">
              <div class="summary">
                <a>Stevie Feliciano</a> added <a>Elliot Fu</a> as a friend
              </div>
            </div>
          </div>
          <div class="event">
            <div class="content">
              <div class="summary">
                <a>Helen Troy</a> added <a>Christian Rocha</a> as a friend
              </div>
            </div>
          </div>
          <div class="event">
            <div class="content">
              <div class="summary">
                <em>Christian Rocha</em>: Test message
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="extra content">
        <form class="ui reply form">
          <div class="field">
            <div class="ui fluid input">
              <input type="text" placeholder="Enter a message...">
              <i class="border inverted orange edit icon large"></i>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
  <div class="four wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content">
        <div class="ui inverted vertical menu">
          <a class="active item">
            Home
          </a>
          <a class="item">
            Messages
          </a>
          <a class="item">
            Friends
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<a class="item" href=" <%= root_path %>">
  Chatroom
</a>
<a class="item">
  Messages
</a>
<div class="right menu">
  <div class="ui dropdown item">
    Account <i class="dropdown icon"></i>
    <div class="menu">
      <a class="item" href=" <%= login_path %>">Log in</a>
      <a class="item">Log out</a>
      <a class="item" href=" <%= root_path %>">Sign up</a>
    </div>
  </div>
  <div class="item">
    <div class="ui primary button">Sign Up</div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApp</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="ui small inverted menu">
      <div class="ui container">
      <%= render "layouts/navigation" %>
      </div>
    </div>
    <div class="ui container">
      <%= yield %>
    </div>
  </body>
</html>